language: java

os: linux

env:
  global:
    - SPARK_MASTER=local[2]


sudo: required

jdk:
  - oraclejdk8

script: mvn clean install cobertura:cobertura

after_success:
  - bash <(curl -s https://codecov.io/bash)